# fly.toml app configuration file generated for sp-cloud-server on 2024-10-17T20:40:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sp-cloud-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
